#!/bin/bash
set -eo pipefail
source /usr/local/PPU_SDK/envsetup.sh >/dev/null
set -u
export PYTHONDONTWRITEBYTECODE=1
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
exec python -B "$(dirname "$(readlink -f "$0")")/entry.py" "$@"
